// import file globa..css
import './globals.css';

import Link from "next/link"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      {/* area header */}
      <header className='text-menu'>
        <Link href={"/"}>Home</Link> | 
        <Link href={"/profil"}>Profil</Link> |
        <Link href={"/visi"}>Visi</Link> |
        Kontak
      </header>
        {children}
        {/* area footer */}
        <footer>
          Copyright &copy; 2024 - Rando - IF 22 C
        </footer>
      </body>
    </html>
  )
}
